config/routes.rb
Rails.application.routes.draw do
  resources :trips
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :travelers, inverse_of: :trip
  has_many :bridges, inverse_of: :trip

  accepts_nested_attributes_for :travelers, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :bridges, reject_if: :all_blank, allow_destroy: true
  after_save :calculate_travel_time

  def self.build_from_json(input_json=nil)
    test_json = "{\"trip\":{\"travelers\":[100,50,25,15,2.5],\"bridges\":[{\"length\":100,\"travelers\":[150]},{\"length\":50,\"travelers\":[10]}]}}"
    parsed_json = JSON.parse(input_json.present? ? input_json : test_json)
    # Set up trip data
    trip_data = parsed_json['trip']
    trip = Trip.new(name: Trip.get_name())
    trip.save!
    # Set up traveler data
    travelers_array = []
    travelers_data = trip_data['travelers']
    travelers_data.each do |traveler_details|
      new_traveler = Traveler.new(speed: traveler_details, name: Traveler.get_name())
      new_traveler.save!
      travelers_array << new_traveler
    end
    trip.travelers = travelers_array
    #  Set up bridge data
    bridges_array = []
    bridges_data = trip_data['bridges']
    bridges_data.each do |bridge_details|
      bridge_length = bridge_details['length']
      bridge_travelers_data = bridge_details['travelers']
      bridge_travelers_array = []
      bridge = Bridge.new(length: bridge_length)
      bridge.save!
      bridge_travelers_data.each do |bridge_traveler|
        new_bridge_traveler = Traveler.new(speed: bridge_traveler, name: Traveler.get_name())
        new_bridge_traveler.save!
        bridge_travelers_array << new_bridge_traveler
      end
      bridge.travelers = bridge_travelers_array
      bridge.save!
      bridges_array << bridge
    end
    trip.bridges = bridges_array
    trip.save!
  end

  def self.get_name
    names = ["Afghanistan","Albania","Algeria","Andorra","Angola","Anguilla","Antigua &amp; Barbuda","Argentina",
             "Armenia","Aruba","Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh","Barbados",
             "Belarus","Belgium","Belize","Benin","Bermuda","Bhutan","Bolivia","Bosnia &amp; Herzegovina",
             "Botswana","Brazil","British Virgin Islands","Brunei","Bulgaria","Burkina Faso","Burundi","Cambodia",
             "Cameroon","Cape Verde","Cayman Islands","Chad","Chile","China","Colombia","Congo","Cook Islands",
             "Costa Rica","Cote D Ivoire","Croatia","Cruise Ship","Cuba","Cyprus","Czech Republic","Denmark",
             "Djibouti","Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea",
             "Estonia","Ethiopia","Falkland Islands","Faroe Islands","Fiji","Finland","France","French Polynesia",
             "French West Indies","Gabon","Gambia","Georgia","Germany","Ghana","Gibraltar","Greece","Greenland",
             "Grenada","Guam","Guatemala","Guernsey","Guinea","Guinea Bissau","Guyana","Haiti","Honduras",
             "Hong Kong","Hungary","Iceland","India","Indonesia","Iran","Iraq","Ireland","Isle of Man","Israel",
             "Italy","Jamaica","Japan","Jersey","Jordan","Kazakhstan","Kenya","Kuwait","Kyrgyz Republic","Laos",
             "Latvia","Lebanon","Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg","Macau",
             "Macedonia","Madagascar","Malawi","Malaysia","Maldives","Mali","Malta","Mauritania","Mauritius","Mexico",
             "Moldova","Monaco","Mongolia","Montenegro","Montserrat","Morocco","Mozambique","Namibia","Nepal",
             "Netherlands","Netherlands Antilles","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria",
             "Norway","Oman","Pakistan","Palestine","Panama","Papua New Guinea","Paraguay","Peru","Philippines",
             "Poland","Portugal","Puerto Rico","Qatar","Reunion","Romania","Russia","Rwanda",
             "Saint Pierre &amp; Miquelon","Samoa","San Marino","Satellite","Saudi Arabia","Senegal","Serbia",
             "Seychelles","Sierra Leone","Singapore","Slovakia","Slovenia","South Africa","South Korea","Spain",
             "Sri Lanka","St Kitts &amp; Nevis","St Lucia","St Vincent","St. Lucia","Sudan","Suriname","Swaziland",
             "Sweden","Switzerland","Syria","Taiwan","Tajikistan","Tanzania","Thailand","Timor L'Este","Togo",
             "Tonga","Trinidad &amp; Tobago","Tunisia","Turkey","Turkmenistan","Turks &amp; Caicos","Uganda","Ukraine",
             "United Arab Emirates","United Kingdom","Uruguay","Uzbekistan","Venezuela","Vietnam","Virgin Islands (US)",
             "Yemen","Zambia","Zimbabwe"]
    names[rand(names.size)]
  end

  private

  def calculate_travel_time
    begin
      self.update_column(:travel_time, self.time(self.persist_party))
    rescue Exception
    end
  end

  def time(persist_new_travelers = false)
    time = 0
    travelers = self.travelers
    self.bridges.each do |bridge|
      if persist_new_travelers
        bridge_travelers = travelers + bridge.prior_new_travelers + bridge.travelers
      else
        bridge_travelers = travelers + bridge.travelers
      end
      length = bridge.length
      start_array = bridge_travelers.sort! { |a,b| b.speed <=> a.speed}
      end_array = []
      loop do
        break if start_array.length == 0
        start_array.sort! { |a,b| b.speed <=> a.speed}
        in_transit = []
        # Calculate Torch Outbound
        if end_array.length == 0
          #Initial Trip
          if start_array.length == 1
            #Only one traveler just send them across
            speed = start_array[0].speed
            in_transit << start_array.delete_at(0)
            in_transit.sort! { |a,b| b.speed <=> a.speed}
            time += length/speed
            end_array << in_transit
            end_array.sort! { |a,b| b.speed <=> a.speed}
          else
            # TODO First trip always sends 2 fastest? Need to double check this isn't even/odd dependent
            in_transit << start_array.delete_at(0)
            in_transit << start_array.delete_at(0)
            in_transit.sort! { |a,b| b.speed <=> a.speed}
            speed = in_transit[1].speed
            time += length/speed
            end_array << in_transit
            end_array.sort! { |a,b| b.speed <=> a.speed}
          end
        else
          #Subsiquint Trips
          if start_array.length.odd?
            # If odd number on start side, send fastest and slowest
            in_transit << start_array.delete_at(0)
            in_transit << start_array.delete_at(start_array.length - 1 )
            in_transit.sort! { |a,b| b.speed <=> a.speed}
            speed = in_transit[1].speed
            time += length/speed
            end_array.sort! { |a,b| b.speed <=> a.speed}
          else
            # If even number on start side, send two slowest
            in_transit << start_array.delete_at(start_array.length - 1 )
            in_transit << start_array.delete_at(start_array.length - 1 )
            in_transit.sort! { |a,b| b.speed <=> a.speed}
            speed = in_transit[1].speed
            time += length/speed
            end_array.sort! { |a,b| b.speed <=> a.speed}
          end
        end
        break if start_array.length == 0
        # Calculate Torch Inbound always send fastest traveler back
        going_back = end_array.delete_at(0)[0]
        time += length/going_back.speed
        start_array << going_back
        start_array.sort! { |a,b| b.speed <=> a.speed}
      end
    end
    time.to_f.round(2)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  def index
    @trips = Trip.all
  end

  # GET /trips/1
  def show
    @trip = Trip.find(params[:id])
  end

  # GET /trips/new
  def new
    @trip = Trip.new
    @trip.travelers.build
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  def create
    @trip = Trip.new(trip_params)

    if @trip.save
      redirect_to(@trip, :notice => 'Trip was successfully created.')
    else
      render :action => "new"
    end
  end

  # PUT /trips/1
  def update
  @trip = Trip.find(params[:id])
    if @trip.update(trip_params)
      redirect_to(@trip, :notice => 'Project was successfully updated.')
    else
      render :action => "edit"
    end
  end

  # DELETE /trips/1
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy
    redirect_to(trips_url)
  end

  private

  def trip_params
    params.require(:trip).permit(
      :name, :persist_party,
      travelers_attributes: [:id, :_destroy, :name, :speed],
      bridges_attributes: [:id, :_destroy, :name, :length, travelers_attributes: [:id, :_destroy, :name, :speed] ],
    )
  end
end

app/views/trips/_bridge_fields.html.erb
<div class='nested-fields'>
  <table class="table">
    <tr>
      <td>
        Bridge Length:
      </td>
      <td>
        <%= f.input :length, label: false %>
      </td>
      <td>
        Bridge Travelers:
      </td>
      <td>
        <div id='bridge-travelers'>
          <%= f.simple_fields_for :travelers do |traveler| %>
            <%= render 'traveler_fields', :f => traveler %>
          <% end %>
          <div class='links'>
            <%= link_to_add_association 'add traveler', f, :travelers %>
          </div>
        </div>
        <%= link_to_remove_association "remove bridge", f %>
      </td>
    </tr>
  </table>
</div>

app/views/trips/_form.html.erb
<%= simple_form_for @trip do |f| %>
  <table class="table">
    <tr>
      <td>
        Trip Name
      </td>
      <td>
        <%= f.input :name, label: false%>
      </td>
    </tr>
    <tr>
      <td>
        Persist Party?
      </td>
      <td>
        <%= f.input :persist_party, label: false%>
      </td>
    </tr>
    <tr>
      <td>
        Travelers
      </td>
      <td>
        <div id='travelers', class='input-group mb-6' }>
          <%= f.simple_fields_for :travelers do |traveler| %>
            <%= render 'traveler_fields', :f => traveler%>
          <% end %>
          <div class='links'>
            <%= link_to_add_association 'add traveler', f, :travelers %>
          </div>
        </div>
      </td>
    </tr>
    <tr>
      <td>Bridges</td>
      <td>
        <div id='bridges', class='input-group mb-6' >
          <%= f.simple_fields_for :bridges do |bridge| %>
            <%= render 'bridge_fields', :f => bridge %>
          <% end %>
          <div class='links'>
            <%= link_to_add_association 'add bridge', f, :bridges%>
          </div>
        </div>
      </td>
    </tr>
  </table>
  <%= f.submit 'Save' %>
<% end %>

app/views/trips/_traveler_fields.html.erb
<div class='nested-fields'>
  <%= f.input :name %>
  <%= f.input :speed %>
  <%= link_to_remove_association "remove traveler", f %>
</div>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form' %>

<%= link_to 'Show', @trip %>
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>List of Trips</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td>
          <%= trip.name %>
        </td>
        <td>
          <%= link_to 'Show', trip, class: 'btn btn-default btn-xs' %>
          <%= link_to 'Edit', edit_trip_path(trip), class: 'btn btn-default btn-xs' %>
          <%= link_to 'Destroy', trip, :confirm => 'You sure bud?', method: :delete, class: 'btn btn-default btn-xs' %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td> Add New </td>
      <td>
        <%= link_to 'New', new_trip_path, class: 'btn btn-default btn-xs' %>
      </td>
    </tr>
  </tbody>
</table>

app/views/trips/new.html.erb
<h1>Plan a cool trip! (bring a light)</h1>

<%= render 'form' %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<table class="table">
  <tr>
    <td>
     Trip Name: <%= @trip.name %>
    </td>
    <td>
      Calculated Trip Time (minutes): <%= @trip.travel_time %>
    </td>

    <td>
      Party Persisted?: <%= @trip.persist_party %>
    </td>
  </tr>
  <tr>
    <td>
      Travelers
    </td>
    <td>
      <table>
        <% @trip.travelers.each do |t|%>
          <tr>
            <td>
              Name:  <%= t.name %>
            </td>
          </tr>
          <tr>
            <td>
              Speed (ft/min): <%= t.speed %>
            </td>
          </tr>
        <% end %>
      </table>
    </td>
  </tr>
  <% @trip.bridges.each do |b|%>
    <tr>
      <td>
        Bridge Number:  <%= b.id %>
      </td>
      <td>
        Bridge Length (ft):  <%= b.length %>
      </td>
      <td>
        <table>
        <% b.travelers.each do |t|%>
          <tr>
            <td>
              Bridge Traveler Name:  <%= t.name %>
            </td>
          </tr>
          <tr>
            <td>
              Bridge Traveler Speed (ft/min): <%= t.speed %>
            </td>
          </tr>
        <% end %>
        </table>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_trip_path(@trip), class: 'btn btn-default btn-xs' %>
<%= link_to 'Back', trips_path %>